# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.item_base_db import ItemBaseDb

class TestItemBaseDb(unittest.TestCase):
    """ItemBaseDb unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemBaseDb:
        """Test ItemBaseDb
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemBaseDb`
        """
        model = ItemBaseDb()
        if include_optional:
            return ItemBaseDb(
                id = 56,
                code = '',
                changed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                active = True,
                brand = '',
                model = '',
                title = '',
                retail_price = 56,
                drop_price = 56,
                link = '',
                photos = '',
                season = '',
                color = '',
                discount_price = 56,
                new = True,
                code_hash = '',
                category_id = '',
                manufacturer_country = '',
                material = '',
                dimension_id = '',
                is_original = True,
                quantities = [
                    swagger_client.models.quantity_base_db.QuantityBaseDb(
                        id = '', 
                        item_id = '', 
                        stock_id = '', 
                        size_id = 56, 
                        count = 56, 
                        centimeter_id = '', 
                        stock = swagger_client.models.stock_base.StockBase(
                            id = '', 
                            name = '', 
                            user_id = 56, 
                            number = 56, 
                            shipment_point = '', 
                            full_name = '', 
                            phone = '', ), 
                        size = swagger_client.models.size_base.SizeBase(
                            id = 56, 
                            value = '', ), 
                        centimeter = swagger_client.models.centimeter_base.CentimeterBase(
                            id = '', 
                            value = '', ), )
                    ],
                category = swagger_client.models.category_base.CategoryBase(
                    id = '', 
                    name = '', ),
                dimension = swagger_client.models.dimension_base.DimensionBase(
                    id = '', 
                    width = 1.337, 
                    height = 1.337, 
                    depth = 1.337, )
            )
        else:
            return ItemBaseDb(
                id = 56,
                code = '',
                code_hash = '',
                category_id = '',
                is_original = True,
        )
        """

    def testItemBaseDb(self):
        """Test ItemBaseDb"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
