# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.api.partners_api import PartnersApi


class TestPartnersApi(unittest.IsolatedAsyncioTestCase):
    """PartnersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PartnersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_partners_user_id_api_v1_partners_get(self) -> None:
        """Test case for get_partners_user_id_api_v1_partners_get

        Get Partners User Id
        """
        pass


if __name__ == '__main__':
    unittest.main()
