# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.api.messages_tg_api import MessagesTgApi


class TestMessagesTgApi(unittest.TestCase):
    """MessagesTgApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesTgApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_messages_tg_name_get(self) -> None:
        """Test case for get_api_v1_messages_tg_name_get

        Get
        """
        pass

    def test_insert_or_update_api_v1_messages_tg_post(self) -> None:
        """Test case for insert_or_update_api_v1_messages_tg_post

        Insert Or Update
        """
        pass


if __name__ == "__main__":
    unittest.main()
