# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.attributes_print_form import AttributesPrintForm

class TestAttributesPrintForm(unittest.TestCase):
    """AttributesPrintForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributesPrintForm:
        """Test AttributesPrintForm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributesPrintForm`
        """
        model = AttributesPrintForm()
        if include_optional:
            return AttributesPrintForm(
                type = '',
                url = ''
            )
        else:
            return AttributesPrintForm(
                type = '',
                url = '',
        )
        """

    def testAttributesPrintForm(self):
        """Test AttributesPrintForm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
