# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.api.quantities_api import QuantitiesApi


class TestQuantitiesApi(unittest.TestCase):
    """QuantitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuantitiesApi()

    def tearDown(self) -> None:
        pass

    def test_insert_or_update_api_v1_quantities_merge_post(self) -> None:
        """Test case for insert_or_update_api_v1_quantities_merge_post

        Insert Or Update
        """
        pass


if __name__ == "__main__":
    unittest.main()
