# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.delivery_cdek_base import DeliveryCdekBase


class TestDeliveryCdekBase(unittest.TestCase):
    """DeliveryCdekBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryCdekBase:
        """Test DeliveryCdekBase
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DeliveryCdekBase`
        """
        model = DeliveryCdekBase()
        if include_optional:
            return DeliveryCdekBase(
                id = 56,
                uuid_id = '',
                tariff_code = 56,
                delivery_point = '',
                create_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 56,
                status_cdek = '',
                cdek_number = '',
                photo_tg_file_id = '',
                invoice_tg_file_id = '',
                courier_to_location = '',
                stock_id = '',
                comment_sender = ''
            )
        else:
            return DeliveryCdekBase(
        )
        """

    def testDeliveryCdekBase(self):
        """Test DeliveryCdekBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
