# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.api.waybills_api import WaybillsApi


class TestWaybillsApi(unittest.TestCase):
    """WaybillsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WaybillsApi()

    def tearDown(self) -> None:
        pass

    def test_update_api_v1_waybills_put(self) -> None:
        """Test case for update_api_v1_waybills_put

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
