# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.item_base import ItemBase

class TestItemBase(unittest.TestCase):
    """ItemBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemBase:
        """Test ItemBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemBase`
        """
        model = ItemBase()
        if include_optional:
            return ItemBase(
                id = 56,
                code = '',
                changed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                active = True,
                brand = '',
                model = '',
                title = '',
                retail_price = 56,
                drop_price = 56,
                link = '',
                photos = '',
                season = '',
                color = '',
                discount_price = 56,
                new = True,
                code_hash = '',
                category_id = '',
                manufacturer_country = '',
                material = '',
                dimension_id = '',
                is_original = True
            )
        else:
            return ItemBase(
        )
        """

    def testItemBase(self):
        """Test ItemBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
