# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from swagger_client.models.info_item_update import InfoItemUpdate

class TestInfoItemUpdate(unittest.TestCase):
    """InfoItemUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfoItemUpdate:
        """Test InfoItemUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfoItemUpdate`
        """
        model = InfoItemUpdate()
        if include_optional:
            return InfoItemUpdate(
                code = '',
                photo_tg_id = ''
            )
        else:
            return InfoItemUpdate(
                code = '',
        )
        """

    def testInfoItemUpdate(self):
        """Test InfoItemUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
