# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.attributes_prealert_closer import AttributesPrealertCloser

class TestAttributesPrealertCloser(unittest.TestCase):
    """AttributesPrealertCloser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributesPrealertCloser:
        """Test AttributesPrealertCloser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributesPrealertCloser`
        """
        model = AttributesPrealertCloser()
        if include_optional:
            return AttributesPrealertCloser(
                prealert_number = '',
                closed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                fact_shipment_point = ''
            )
        else:
            return AttributesPrealertCloser(
                prealert_number = '',
                closed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                fact_shipment_point = '',
        )
        """

    def testAttributesPrealertCloser(self):
        """Test AttributesPrealertCloser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
