# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.api.barcodes_api import BarcodesApi


class TestBarcodesApi(unittest.IsolatedAsyncioTestCase):
    """BarcodesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BarcodesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_insert_api_v1_barcodes_post(self) -> None:
        """Test case for insert_api_v1_barcodes_post

        Insert
        """
        pass


if __name__ == '__main__':
    unittest.main()
