# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.api.sizes_api import SizesApi


class TestSizesApi(unittest.TestCase):
    """SizesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SizesApi()

    def tearDown(self) -> None:
        pass

    def test_get_size_by_id_api_v1_sizes_size_id_get(self) -> None:
        """Test case for get_size_by_id_api_v1_sizes_size_id_get

        Get Size By Id
        """
        pass

    def test_get_sizes_api_v1_sizes_get(self) -> None:
        """Test case for get_sizes_api_v1_sizes_get

        Get Sizes
        """
        pass

    def test_insert_or_nothing_api_v1_sizes_post(self) -> None:
        """Test case for insert_or_nothing_api_v1_sizes_post

        Insert Or Nothing
        """
        pass


if __name__ == "__main__":
    unittest.main()
