# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.t_bank_payment_db import TBankPaymentDb

class TestTBankPaymentDb(unittest.TestCase):
    """TBankPaymentDb unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TBankPaymentDb:
        """Test TBankPaymentDb
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TBankPaymentDb`
        """
        model = TBankPaymentDb()
        if include_optional:
            return TBankPaymentDb(
                id = 56,
                tbank_kassa_id = 56,
                order_id = 56,
                tbank_payment_id = '',
                tbank_status = '',
                tbank_order_id = '',
                tbank_amount = 56,
                tbank_payment_url = '',
                tbank_redirect_due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                create_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                update_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TBankPaymentDb(
                id = 56,
                tbank_kassa_id = 56,
                order_id = 56,
                tbank_payment_id = '',
                tbank_status = '',
                tbank_order_id = '',
                tbank_amount = 56,
                tbank_payment_url = '',
                tbank_redirect_due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                create_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                update_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTBankPaymentDb(self):
        """Test TBankPaymentDb"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
