# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.insert_basket import InsertBasket


class TestInsertBasket(unittest.TestCase):
    """InsertBasket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsertBasket:
        """Test InsertBasket
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsertBasket`
        """
        model = InsertBasket()
        if include_optional:
            return InsertBasket(
                user_bot_id = 56,
                size_id = 56,
                price = 56,
                code = ''
            )
        else:
            return InsertBasket(
                user_bot_id = 56,
                size_id = 56,
                price = 56,
                code = '',
        )
        """

    def testInsertBasket(self):
        """Test InsertBasket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
