# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.api.tbank_kasses_api import TbankKassesApi


class TestTbankKassesApi(unittest.TestCase):
    """TbankKassesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TbankKassesApi()

    def tearDown(self) -> None:
        pass

    def test_insert_api_v1_tbank_kasses_post(self) -> None:
        """Test case for insert_api_v1_tbank_kasses_post

        Insert
        """
        pass


if __name__ == '__main__':
    unittest.main()
