# coding: utf-8

"""
    Rest DB

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from swagger_client.models.insert_t_bank_kassa import InsertTBankKassa

class TestInsertTBankKassa(unittest.TestCase):
    """InsertTBankKassa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsertTBankKassa:
        """Test InsertTBankKassa
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsertTBankKassa`
        """
        model = InsertTBankKassa()
        if include_optional:
            return InsertTBankKassa(
                bot_id = 56,
                terminal_key = bytes(b'blah'),
                password = bytes(b'blah')
            )
        else:
            return InsertTBankKassa(
                bot_id = 56,
                terminal_key = bytes(b'blah'),
                password = bytes(b'blah'),
        )
        """

    def testInsertTBankKassa(self):
        """Test InsertTBankKassa"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
