version: 2
updates:
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
